### ISSUE TITLE
Prototype design

### ISSUE THREAD

**Issue by dubhcait** [FAC-Sixteen/LSx#1]
1. Currently designing for a child audience first and starting with the 1st user journey.
2. Initially designing mobile first as converting a mobile design to a desktop one is quicker than the reverse. 

User testing question - Desktop Vs Mobile
Are there any other user questions that you want to ask the users?
Or suggestions in the direction we should gear the design?

**Comment by dubhcait** [comment]
We have been honing in on the action plan idea. So we are going to try a design a form where people answer a series of question and at the end, they have an action plan built based on their answers. 

So can you figure out what questions would be best to ask?
Also, can you suggest 3 answers for each question? So we can use them in the form.
You probably have resources already you can pull stuff out of.

**Comment by jalexanderrr** [comment]
After a bit of thinking and talking with the team I think a mobile app would be more dynamic / useful for our project work.
With a mobile app we can include 'lite' versions of our toolkits within the app. Full PDF toolkits and further resources can be sent to a designated user email address for a small donation (say £3). (My bosses are a bit tired of giving away our intellectual property for free)

You've sort of lost me on the question thing tbh. It sounds a little formulaic. The app doesn't have to design the action plan for the user but should support the user in arriving at their own action plan. We can provide examples of data collection methods (+the pros and cons) and action plan examples (+ good news stories) to help inspire the user.

I do think a question flow chart could be really useful for users in navigating to the right part of the app for them (maybe that's what you meant).

Also regarding the name of the app "Community AQ Portal by LSx" or "LSx Community Portal"

Also re thursday morning: Yes please. At our office. Ben and Alice (our senior project team are around until 11). I've invited a load of past volunteers but it's quite late notice / no joy yet. Hugh will also be there (the volunteer helping us to write about the pros and cons of diffusion tube experiments). And also Gail, my boos, though she may be quite busy.

**Comment by dubhcait** [comment]
The 'lite' versions of toolkits within the app and full versions for a small donation is a really good idea and would fit really well. 

We've kind of took it less formulaic and more like a grassroots action plan. Like this..

 ![](https://i.imgur.com/r7W0ID4.png)

So more in a motivation kind of way. like 3 key questions where you get to choose what you want to do and it is filled into a grid that is sent to their email. With a lite version of a toolkit if relevant.
It would be just a simple thing to get people started. The emphases would be sharing the stories online.
What do you think?

With regards to the name, we are not really sure what a portal is. We had been thinking of the app as a way to get people started. We went back over the user research and were thinking LSx Action Planner but the meat of the app is showing people what they can do with the success stories. 

Perfect in regards thursday, we'll see you then.

**Comment by jalexanderrr** [comment]
Really like the look of this. Very promising.
Thoughts on questions so far…

Measuring
Air pollution is an invisible threat. A really important part about creating change is making pollution ‘visible’. You can do this by collecting data and air pollution measurements.

·         How can I ‘see’/ ‘make visible’ air pollution in my area?
Diffusion tubes/ lichen walks/ tertiary data
(supporting information about pros and cons)

Objectives (optional, not all users will have considered this)
It is important to consider an objective or a goal that you would like to reach
                Moving a bus route /

Interpretation (helping user to interpret findings)
Consider the nature of pollution in your area.
How does the data you have collect provide evidence of that pollution

·         What does my data tell me about the nature of the pollution threat in your area?
High NO2 near bus routes/cab ranks/airports
High particulate reading near building sites / roads / industry

Connecting
You have identified the threat of air pollution in your area. Teaming up with other people and groups who are fighting pollution near you will make your voice louder and make it easier to reach you objectives.

·         Who else is tackling air pollution in my area?

N/S/E/W/C

-          Names of action groups

-          Names/email addresses of other app users (if they agree to share their contact details)

Actions
You have identified there is an issue with air pollution in your area. You can contact local government and make them aware of the issue. But the best way to make a change is to develop your own action plan and get you community to help you.

·         What actions can I implement in my community
Create an awareness campaign/ green screening – hedges / active travel choices / ask for a bus stop to be moved / asked for a play street outside your school / avoidance - walk quieter routes – eat healthy / batch-order deliveries (fewer vans on the road)
                (backed up with examples and case studies ‘good news’)
                Can have a community pledge template and ways of sharing that to our social media.

I’ve got to go now. I’m having friend’s for dinner.
I’m out on a project tomorrow morning.
Can answer more in the afternoon.
Give me a call on the office line after 1 if you’re stuck

Best, J

**Comment by dubhcait** [comment]
Love your ideas. Just putting some final touches for the prototype for tomorrow.

**Comment by dubhcait** [comment]
https://www.figma.com/proto/UooJqSQKCdIf2ojz04U6cJzj/lsx?node-id=25%3A3&scaling=fit-width&redirected=1

**Comment by hrmstockdale** [comment]
Afternoon Jack,

Please see the links below to a google form to fill in for any additional user testing and a link to the prototype itself.

https://docs.google.com/forms/d/e/1FAIpQLScUaab9ZcTgNvjimoyXbSaZ5JH9xypPaQhN8yxeDos717-FPw/viewform?usp=sf_link

https://www.figma.com/file/UooJqSQKCdIf2ojz04U6cJzj/lsx?node-id=6%3A2

Two things to bear in mind:
1. Users can be kept anonymous
2. If there is anything unclear in the document please do not refrain from reaching out to us :) 

Have a fab weekend (hopefully ft. more optimistic weather)

H
